<h1>Kontakt</h1>
<form method="post" action="">
    <table width="100%">
        <tr>
            <td><input style="width: 100%; border: solid 1px #ccc; padding: 10px 15px; box-sizing: border-box; border-radius: 2px; margin-bottom: 5px;" type="text" name="lastname" placeholder="Twoje imię"></td>
        </tr>
        <tr>
            <td><input style="width: 100%; border: solid 1px #ccc; padding: 10px 15px; box-sizing: border-box; border-radius: 2px; margin-bottom: 5px;" type="text" name="lastname" placeholder="Twój E-mail"></td>
        </tr>
        <tr>
            <td><input style="width: 100%; border: solid 1px #ccc; padding: 10px 15px; box-sizing: border-box; border-radius: 2px; margin-bottom: 5px;" type="text" name="lastname" placeholder="Twoja wiadomość"></td>
        </tr>
        <tr>
            <td><input style="background: #5ca801; border: solid 0px #ffffff; color: #ffffff; padding: 10px 50px;" type="submit" value="Wyślij"></td>
        </tr>
    </table>
</form>