<h1>Regulamin</h1>
<h4>1. POSTANOWIENIA OGÓLNE</h4>

1.1 Portal SPORT-CAST.pl jest serwisem internetowym zbierającym w jednym miejscu streamy (kanały). Streamy może dodać każdy Użytkownik portalu SPORT-CAST.pl poprzez specjalnie stworzony do tego formularz. Portal SPORT-CAST.pl nie jest właścicielem żadnego kanału umieszczonego na stronie.
<br/><br/>
1.2 Treści zamieszczane w Portalu SPORT-CAST.pl są dostępne dla wszystkich użytkowników Internetu bez żadnej dodatkowej opłaty.
<br/><br/>
1.3 Użytkownik Portalu SPORT-CAST.pl korzystając z niego zaświadcza, że zapoznał się z regulaminem Portalu.
<br/><br/>
1.4 Określenia użyte w niniejszym Regulaminie posiadają następujące znaczenie:
<br/><br/>
1.4.1 Regulamin – niniejszy dokument w aktualnie obowiązującej wersji, znajdujący się pod adresem http://www.SPORT-CAST.pl/user/regulamin stanowiący regulamin świadczenia usług drogą elektroniczną w rozumieniu ustawy z dnia 18 lipca 2002 r. o świadczeniu usług drogą elektroniczną.
<br/><br/>
1.4.2 Portal – zbiór stron www zlokalizowanych w domenie http://www.SPORT-CAST.pl/, stanowiący własność Administratora, umożliwiający między innymi umieszczanie Użytkownikom w tym Portalu Materiałów w celu ich publikacji w Internecie i udostępnienia pozostałym Użytkownikom.
<br/><br/>
1.4.3 Użytkownik - osoba korzystająca z Portalu. Użytkownikiem Portalu może być osoba pełnoletnia, posiadająca pełną zdolność do czynności prawnych, a osoba małoletnia tylko za zgodą przedstawiciela ustawowego.
<br/><br/>
1.4.4 Materiały – streamy (kanał) oraz inne treści zamieszczone przez Użytkownika na serwerach Administratora w celu ich publikacji w Portalu w formie Linku lub pliku o określonych parametrach (w tym w formie tzw. obiektu osadzonego).
<br/><br/>
1.4.5 Link - odnośnik przekierowujący do strony internetowej, na której zamieszczony jest Materiał.
<br/><br/>
1.4.6 Obiekt Osadzony – Materiał w formie obiektu osadzonego w kodzie stron Portalu przez Administratora lub Użytkownika (poprzez specjalny formularz do tego stworzony).
<br/><br/>
1.4.7 Nadużycie – wszelkie działania Użytkownika niezgodne z niniejszym Regulaminem.

<h4>2. ZASADY UMIESZCZANIA MATERIAŁÓW NA SERWERACH ADMINISTRATORA</h4>

2.1 Użytkownicy mogą zamieszczać na serwerach Administratora, w celu publikacji w Portalu, Materiały opatrzone tytułem. Administrator zastrzega sobie możliwość zmiany, dodania lub usunięcia statusu zamieszczonego przez Użytkownika, w przypadku nadużycia
<br/><br/>
2.2 Administrator nie ingeruje w treść Materiałów oraz nie ponosi odpowiedzialności za ewentualne szkody wywołane ich publikacją. Administrator zastrzega sobie prawo do usunięcia Materiałów w przypadku stwierdzenia, iż mogą naruszać chronione prawem dobra podmiotów trzecich lub naruszają dobre zwyczaje.
<br/><br/>
2.3 Użytkownik umieszczając jakiekolwiek Materiały oświadcza, iż są one wolne od wad prawnych oraz roszczeń podmiotów trzecich oraz, że przysługują mu majątkowe prawa autorskie do treści, które nie są ograniczone na rzecz żadnej osoby trzeciej lub, że przysługują mu prawa do korzystania z tych treści, w tym prawo do wykorzystania wizerunku osoby trzeciej, obejmujące w szczególności prawo do publikowania i rozpowszechniania Materiałów w systemie on-line, w sieci Internet.
<br/><br/>
2.4 Korzystanie z Portalu, w tym zamieszczanie Materiałów, nie podlega opłatom.
<br/><br/>
2.5 Użytkownik ponosi pełną i nieograniczoną odpowiedzialność za wszystkie Materiały, które zamieścił w Portalu.
<br/><br/>
2.6 Użytkownik zobowiązuje się, że w momencie wystąpienia przez osoby trzecie z roszczeniami w stosunku do Administratora z tytułu naruszenia jakichkolwiek ich praw przez zamieszczenie Materiału lub innej treści przez Użytkownika, Użytkownik ten wstąpi do sprawy w miejsce Administratora lub przystąpi do sprawy w charakterze interwenienta ubocznego oraz przejmie na siebie w całości koszty ewentualnego postępowania sądowego, koszty zastępstwa procesowego oraz zasądzonych lub ustalonych w drodze ugody odszkodowań.
<br/><br/>
2.7 Użytkownik może w każdym momencie zaprzestać korzystania z Portalu.
<br/><br/>
2.8 Jeżeli zdaniem Użytkownika Materiał narusza prawo, Regulamin lub dobre obyczaje, Użytkownik ma możliwość zawiadomienia o tym fakcie Administratora za pomocą przycisku „Zgłoś nadużycie” umieszczonego na Portalu.

<h4>3. OBOWIĄZKI UŻYTKOWNIKA</h4>

3.1 Użytkownik zobowiązuje się do korzystania z Portalu zgodnie z obowiązującymi w Polsce przepisami prawa, normami społecznymi i obyczajowymi, postanowieniami niniejszego Regulaminu oraz zasadami współżycia społecznego, a w szczególności do:
<br/><br/>
a) nie zamieszczania na chacie oraz Portalu treści o charakterze bezprawnym, w jakikolwiek sposób naruszających prawo, sprzecznych z dobrymi obyczajami, a w szczególności zawierających treści pornograficzne, obrażające uczucia religijne, wzywających do nienawiści rasowej, etnicznej, wyznaniowej, propagujących piractwo fonograficzne, komputerowe, upowszechniających techniki łamania danych, wirusy i inne podobne,
<br/><br/>
b) działania w sposób nie naruszający praw innych Użytkowników, w tym w szczególności majątkowych i osobistych praw autorskich oraz ich prawa do prywatności,
<br/><br/>
c) nie zamieszczanie na chacie oraz Portalu treści oraz elementy graficzne o charakterze komercyjnym, reklamowym,
<br/><br/>
d) nie podejmowania działań i zamieszczania Materiałów, które mogłyby utrudnić lub uniemożliwić funkcjonowanie Portalu,
<br/><br/>
e) nie używania w Materiałach lub na chacie nicków, tytułów, opisów, treści itp. będących lub nawiązujących do wyrazów powszechnie uznanych za obraźliwe i niezgodne z dobrymi obyczajami.
<br/><br/>
3.2 W przypadku odmowy przez Użytkownika usunięcia treści o których mowa w punkcie 3.1., Administrator ma prawo usunąć je samodzielnie.

<h4>4. ODPOWIEDZIALNOŚĆ, PRAWA ORAZ OBOWIĄZKI ADMINISTRATORA</h4>

4.1 Administrator nie ponosi odpowiedzialności za:
<br/><br/>
a) sposób korzystania z Portalu przez Użytkowników i skutki korzystania z Portalu,
<br/><br/>
b) treść i formę zamieszczanych Materiałów oraz za prawdziwość treści i danych umieszczanych przez Użytkownika,
c) treść i formę opisów charakteryzujących Użytkowników,
<br/><br/>
d) niezamierzone i niezawinione błędy w działaniu aplikacji udostępnianych Użytkownikom w ramach Portalu,
<br/><br/>
e) szkody wynikłe z udostępnienia przez Użytkownika hasła dostępowego do Konta na chacie osobom trzecim, niezależnie od przyczyny, która to spowodowała (np. udostępnienie hasła osobie trzeciej przez Użytkownika, złamanie hasła przez osobę trzecią),
<br/><br/>
f) udostępnianie hasła i danych Użytkowników osobom upoważnionym na podstawie właściwych przepisów prawa bądź stosownych decyzji administracyjnych lub orzeczeń sądowych,
<br/><br/>
g) utratę Materiałów zamieszczonych w Portalu spowodowaną awarią sprzętu, dysfunkcją Internetu, działaniem osób trzecich lub ich usunięciem przez Administratora na podstawie przepisów Regulaminu lub przepisów prawa,
<br/><br/>
4.2 Administrator zastrzega sobie prawo do:
<br/><br/>
a) okresowego wyłączania, w uzasadnionych przypadkach, Portalu bez uprzedniego powiadomienia Użytkowników,
<br/><br/>
b) Materiału bez uprzedniego powiadomienia, w wypadku naruszenia przez Użytkownika postanowień niniejszego Regulaminu,
<br/><br/>
c) natychmiastowego skasowania każdego Materiału, co do którego istnieje podejrzenie, że może on naruszać prawo, dobre obyczaje, uczucia, w tym uczucia religijne, oraz prawa osób trzecich,
<br/><br/>
d) zaprzestania udostępniania Portalu lub jego poszczególnych funkcjonalności, po uprzednim powiadomieniu Użytkowników na stronach Portalu,
<br/><br/>
e) skasowania, w sytuacjach wyjątkowych, nie zawinionych przez Administratora, całej zawartości Portalu.
<br/><br/>
4.3 Zakres dostępu lub sposób funkcjonowania Portalu może być w każdym czasie zmieniany (rozszerzany lub ograniczany) przez Administratora. Administrator będzie informował na łamach Portalu o każdej zmianie zakresu udostępnianych funkcjonalności.

<h4>5. REKLAMACJE (Tryb i sposób składania reklamacji)</h4>

5.1 Każdemu Użytkownikowi Portalu przysługuje prawo do złożenia reklamacji w sprawach związanych z funkcjonowaniem Portalu.
<br/><br/>
5.2 Reklamacje należy składać drogą elektroniczną na adres maila Administratora
<br/><br/>
5.3 Administrator rozpatrzy reklamację w terminie 14 dni roboczych od dnia jej otrzymania.
<br/><br/>
5.4 Odpowiedź na reklamację zostanie przesłana do Użytkownika na adres podany przez Użytkownika w reklamacji.
<br/><br/>
5.5 Administrator zastrzega sobie prawo do wydłużenia terminu podanego w pkt 6.3. w przypadku, gdy rozpoznanie reklamacji wymaga wiadomości specjalnych, lub napotka przeszkody z przyczyn od niego niezależnych (awarie sprzętu, sieci internetowej itp.). Administrator ponadto zastrzega, że rozpatrzenie reklamacji może wymagać uzyskania od Użytkownika dodatkowych wyjaśnień - czas udzielania wyjaśnień przez Użytkownika każdorazowo przedłuża okres rozpoznania reklamacji.

<h4>6. ZMIANA REGULAMINU</h4>

6.1 Wszelkie postanowienia Regulaminu mogą być w każdej chwili zmieniane przez Administratora, bez podawania przyczyn. Zmiany będą publikowane na bieżąco w postaci ujednoliconego tekstu Regulaminu na łamach Portalu wraz z informacją o ich dokonaniu.
<br/><br/>
6.2 Po ukazaniu się na stronie głównej Portalu lub w innych miejscach do tego przeznaczonych w Portalu informacji o zmianach w Regulaminie, Użytkownik powinien niezwłocznie zapoznać się ze zmianami, gdyż zalogowanie do Portalu po takim ogłoszeniu stanowi bezwarunkową akceptację nowej treści Regulaminu przez Użytkownika.